version: "3.9"

services:

  backend:
    build: ./backend
    dns:
      - 8.8.8.8
      - 1.1.1.1
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
