-- สร้างตารางสินค้า (Catalog)
CREATE TABLE catalog_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  description TEXT,
  stock INT DEFAULT 1,
  location TEXT,
  status TEXT DEFAULT 'available', -- 'available', 'out_of_stock'
  condition TEXT,
  image_url TEXT
);

-- เพิ่มข้อมูลตัวอย่าง (Mock Data)
INSERT INTO catalog_items (name, category, description, stock, location, status, condition, image_url) VALUES
('MacBook Pro M3', 'Electronics', 'test', 5, 'csb', 'available', 'excellent', '💻'),
('Arduino Uno R3', 'Electronics', 'test', 5, 'csb', 'available', 'good', '🤖'),
('Projector Sony', 'Manufacturing', 'test', 0, 'csb', 'not_available', 'excellent', '📽️'),
('DSLR Camera', 'Manufacturing', 'test', 5, 'csb', 'available', 'bad', '📷');
