-- 1. สร้างตารางเก็บข้อมูลผู้ใช้ (Profiles)
CREATE TABLE profiles (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    avatar_url TEXT
);

-- 2. จำลองข้อมูลผู้ใช้ 2 คนเข้าระบบ
INSERT INTO profiles (id, name, email, avatar_url) VALUES
('user_001', 'สมชาย ทรงแบด', 'somchai@gmail.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Somchai'),
('user_002', 'สมหญิง สายหวาน', 'somying@gmail.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Somying');

-- 3. ลบตาราง borrow_items เก่าทิ้ง และสร้างใหม่โดยมี user_id
CREATE TABLE borrow_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES profiles(id), -- คอลัมน์นี้สำคัญมาก! ใช้ผูกว่าใครยืม
    name TEXT NOT NULL,
    category TEXT,
    stock INT DEFAULT 1,
    borrow_date TEXT,
    return_date TEXT,
    location TEXT,
    status TEXT,
    image_url TEXT
);

-- 4. จำลองข้อมูลการยืม โดยแยกให้ user_001 และ user_002 ยืมของคนละชิ้น
INSERT INTO borrow_items (user_id, name, category, stock, borrow_date, return_date, location, status, image_url) VALUES
('user_001', 'MacBook Pro M2', 'Laptop', 1, '', '', '', 'approve', ''),
('user_001', 'Projector Epson EB-X06', 'Projector', 1, '19-02-2026', '', '', 'reject', ''),
('user_002', 'สาย HDMI 5 เมตร', 'Cable', 2, '', '', '', 'late', ''),
('user_002', 'Review Item', 'Other', 1, '20-02-2026', '27-02-2026', 'CSB', 'waiting', '');